"""empty message

Revision ID: 904f1cf88ef7
Revises: 
Create Date: 2021-09-17 16:49:52.976297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904f1cf88ef7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
